#! /usr/bin/env bash -e


# Add additional repos
echo -e "\nEnabling repositories ...\n"
dnf -y install \
    fedora-workstation-repositories \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-"$(rpm -E %fedora)".noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-"$(rpm -E %fedora)".noarch.rpm


# Update with new repos
dnf -y update || true


# Install package groups
echo -e "\nInstalling package groups...\n"
dnf -y group install  \
    base-x \
    core \
    standard \
    virtualization \
    'hardware support'


# Install xfce minimal desktop
echo -e "\nInstalling Xfce desktop...\n"
dnf -y --setopt=install_weak_deps=False install \
    exo \
    garcon \
    libxfce4ui \
    libxfce4util \
    thunar \
    thunar-volman \
    tumbler \
    xfce4-notifyd \
    xfce4-panel \
    xfce4-pulseaudio-plugin \
    xfce4-power-manager \
    xfce4-screenshooter \
    xfce4-session \
    xfce4-settings \
    xfce4-terminal \
    xfconf \
    xfdesktop \
    xfwm4 \
    lxdm

systemctl enable lxdm
systemctl set-default graphical.target


# Install additional packages
echo -e "\nInstalling additional applications ...\n"
dnf -y --setopt=install_weak_deps=False install \
    alsa-utils \
    dconf \
    dnf-automatic \
    ffmpeg \
    file-roller \
    firefox \
    firejail \
    git \
    greybird-dark-theme \
    gvfs \
    htop \
    NetworkManager \
    NetworkManager-wifi \
    nm-connection-editor \
    papirus-icon-theme \
    shotwell \
    transmission-gtk \
    vlc \
    xed \
    xreader

systemctl enable NetworkManager


# Install nordvpn
echo -e "\nInstalling NordVPN ...\n"
yes | sh <(curl -sSf https://downloads.nordcdn.com/apps/linux/install.sh)