#!/usr/bin/env bash

set -e


# Add additional Fedora repos
echo -e "\nEnabling additional repositories ...\n"
dnf -y install \
    fedora-workstation-repositories \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-"$(rpm -E %fedora)".noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-"$(rpm -E %fedora)".noarch.rpm


# DNF update with new repos
dnf -y update --refresh || true


# Install package groups
echo -e "\nInstalling Fedora package groups...\n"
dnf -y group install  \
    base-x \
    core \
    standard \
    virtualization \
    'hardware support'


# Install bare bones xfce
echo -e "\nInstalling Xfce desktop ...\n"
dnf -y --setopt=install_weak_deps=False install \
    exo \
    garcon \
    libxfce4ui \
    libxfce4util \
    lxdm \
    thunar \
    thunar-archive-plugin \
    thunar-volman \
    tumbler \
    xfce4-notifyd \
    xfce4-panel \
    xfce4-pulseaudio-plugin \
    xfce4-power-manager \
    xfce4-screenshooter \
    xfce4-session \
    xfce4-settings \
    xfce4-terminal \
    xfconf \
    xfdesktop \
    xfwm4


# Install additional packages
echo -e "\nInstalling additional applications ...\n"
dnf -y --setopt=install_weak_deps=False install \
    alsa-utils \
    dconf \
    dnf-automatic \
    ffmpeg-free \
    firefox \
    firejail \
    git \
    greybird-dark-theme \
    gvfs \
    htop \
    network-manager-applet \
    papirus-icon-theme \
    ristretto \
    transmission-gtk \
    vlc \
    xarchiver \
    xed \
    xreader


# Install nordvpn
echo -e "\nInstalling NordVPN ...\n"
yes | sh <(curl -sSf https://downloads.nordcdn.com/apps/linux/install.sh)
